version: '3'

services:
  postgres:
    image: postgres:12.9-alpine
    container_name: sample-postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

volumes:
  pg_data:
